
production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
  port: <%= ENV['RDS_PORT'] %>

