require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NadaservesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Nadaserve. As you add validations to Nadaserve, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NadaservesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all nadaserves as @nadaserves" do
      nadaserve = Nadaserve.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:nadaserves)).to eq([nadaserve])
    end
  end

  describe "GET #show" do
    it "assigns the requested nadaserve as @nadaserve" do
      nadaserve = Nadaserve.create! valid_attributes
      get :show, {:id => nadaserve.to_param}, valid_session
      expect(assigns(:nadaserve)).to eq(nadaserve)
    end
  end

  describe "GET #new" do
    it "assigns a new nadaserve as @nadaserve" do
      get :new, {}, valid_session
      expect(assigns(:nadaserve)).to be_a_new(Nadaserve)
    end
  end

  describe "GET #edit" do
    it "assigns the requested nadaserve as @nadaserve" do
      nadaserve = Nadaserve.create! valid_attributes
      get :edit, {:id => nadaserve.to_param}, valid_session
      expect(assigns(:nadaserve)).to eq(nadaserve)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Nadaserve" do
        expect {
          post :create, {:nadaserve => valid_attributes}, valid_session
        }.to change(Nadaserve, :count).by(1)
      end

      it "assigns a newly created nadaserve as @nadaserve" do
        post :create, {:nadaserve => valid_attributes}, valid_session
        expect(assigns(:nadaserve)).to be_a(Nadaserve)
        expect(assigns(:nadaserve)).to be_persisted
      end

      it "redirects to the created nadaserve" do
        post :create, {:nadaserve => valid_attributes}, valid_session
        expect(response).to redirect_to(Nadaserve.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved nadaserve as @nadaserve" do
        post :create, {:nadaserve => invalid_attributes}, valid_session
        expect(assigns(:nadaserve)).to be_a_new(Nadaserve)
      end

      it "re-renders the 'new' template" do
        post :create, {:nadaserve => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested nadaserve" do
        nadaserve = Nadaserve.create! valid_attributes
        put :update, {:id => nadaserve.to_param, :nadaserve => new_attributes}, valid_session
        nadaserve.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested nadaserve as @nadaserve" do
        nadaserve = Nadaserve.create! valid_attributes
        put :update, {:id => nadaserve.to_param, :nadaserve => valid_attributes}, valid_session
        expect(assigns(:nadaserve)).to eq(nadaserve)
      end

      it "redirects to the nadaserve" do
        nadaserve = Nadaserve.create! valid_attributes
        put :update, {:id => nadaserve.to_param, :nadaserve => valid_attributes}, valid_session
        expect(response).to redirect_to(nadaserve)
      end
    end

    context "with invalid params" do
      it "assigns the nadaserve as @nadaserve" do
        nadaserve = Nadaserve.create! valid_attributes
        put :update, {:id => nadaserve.to_param, :nadaserve => invalid_attributes}, valid_session
        expect(assigns(:nadaserve)).to eq(nadaserve)
      end

      it "re-renders the 'edit' template" do
        nadaserve = Nadaserve.create! valid_attributes
        put :update, {:id => nadaserve.to_param, :nadaserve => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested nadaserve" do
      nadaserve = Nadaserve.create! valid_attributes
      expect {
        delete :destroy, {:id => nadaserve.to_param}, valid_session
      }.to change(Nadaserve, :count).by(-1)
    end

    it "redirects to the nadaserves list" do
      nadaserve = Nadaserve.create! valid_attributes
      delete :destroy, {:id => nadaserve.to_param}, valid_session
      expect(response).to redirect_to(nadaserves_url)
    end
  end

end
