require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NetworkAnalyticsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # NetworkAnalytic. As you add validations to NetworkAnalytic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NetworkAnalyticsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all network_analytics as @network_analytics" do
      network_analytic = NetworkAnalytic.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:network_analytics)).to eq([network_analytic])
    end
  end

  describe "GET #show" do
    it "assigns the requested network_analytic as @network_analytic" do
      network_analytic = NetworkAnalytic.create! valid_attributes
      get :show, {:id => network_analytic.to_param}, valid_session
      expect(assigns(:network_analytic)).to eq(network_analytic)
    end
  end

  describe "GET #new" do
    it "assigns a new network_analytic as @network_analytic" do
      get :new, {}, valid_session
      expect(assigns(:network_analytic)).to be_a_new(NetworkAnalytic)
    end
  end

  describe "GET #edit" do
    it "assigns the requested network_analytic as @network_analytic" do
      network_analytic = NetworkAnalytic.create! valid_attributes
      get :edit, {:id => network_analytic.to_param}, valid_session
      expect(assigns(:network_analytic)).to eq(network_analytic)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new NetworkAnalytic" do
        expect {
          post :create, {:network_analytic => valid_attributes}, valid_session
        }.to change(NetworkAnalytic, :count).by(1)
      end

      it "assigns a newly created network_analytic as @network_analytic" do
        post :create, {:network_analytic => valid_attributes}, valid_session
        expect(assigns(:network_analytic)).to be_a(NetworkAnalytic)
        expect(assigns(:network_analytic)).to be_persisted
      end

      it "redirects to the created network_analytic" do
        post :create, {:network_analytic => valid_attributes}, valid_session
        expect(response).to redirect_to(NetworkAnalytic.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved network_analytic as @network_analytic" do
        post :create, {:network_analytic => invalid_attributes}, valid_session
        expect(assigns(:network_analytic)).to be_a_new(NetworkAnalytic)
      end

      it "re-renders the 'new' template" do
        post :create, {:network_analytic => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested network_analytic" do
        network_analytic = NetworkAnalytic.create! valid_attributes
        put :update, {:id => network_analytic.to_param, :network_analytic => new_attributes}, valid_session
        network_analytic.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested network_analytic as @network_analytic" do
        network_analytic = NetworkAnalytic.create! valid_attributes
        put :update, {:id => network_analytic.to_param, :network_analytic => valid_attributes}, valid_session
        expect(assigns(:network_analytic)).to eq(network_analytic)
      end

      it "redirects to the network_analytic" do
        network_analytic = NetworkAnalytic.create! valid_attributes
        put :update, {:id => network_analytic.to_param, :network_analytic => valid_attributes}, valid_session
        expect(response).to redirect_to(network_analytic)
      end
    end

    context "with invalid params" do
      it "assigns the network_analytic as @network_analytic" do
        network_analytic = NetworkAnalytic.create! valid_attributes
        put :update, {:id => network_analytic.to_param, :network_analytic => invalid_attributes}, valid_session
        expect(assigns(:network_analytic)).to eq(network_analytic)
      end

      it "re-renders the 'edit' template" do
        network_analytic = NetworkAnalytic.create! valid_attributes
        put :update, {:id => network_analytic.to_param, :network_analytic => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested network_analytic" do
      network_analytic = NetworkAnalytic.create! valid_attributes
      expect {
        delete :destroy, {:id => network_analytic.to_param}, valid_session
      }.to change(NetworkAnalytic, :count).by(-1)
    end

    it "redirects to the network_analytics list" do
      network_analytic = NetworkAnalytic.create! valid_attributes
      delete :destroy, {:id => network_analytic.to_param}, valid_session
      expect(response).to redirect_to(network_analytics_url)
    end
  end

end
